### ISSUE TITLE
SecureRandom is (considered) better than Random (although, admittedly, for this little demo it may be meaningless)

### ISSUE THREAD

**Issue by royshahaf** [jkschneider/multi-foundation-metrics#1]
https://github.com/jkschneider/multi-foundation-metrics/blob/3ec348e894b43305f46ffee12c0fb13add38a427/src/main/java/io/pivotal/spinnaker/multifoundationmetrics/DataImportConfiguration.java#L36

**Comment by jkschneider** [comment]
Thanks, I'll use that in the future ;)
